name: Build Game Libraries

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          pkg-config \
          libasound2-dev \
          libpulse-dev \
          libaudio-dev \
          libjack-dev \
          libsndio-dev \
          libx11-dev \
          libxext-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxfixes-dev \
          libxi-dev \
          libxinerama-dev \
          libxxf86vm-dev \
          libxss-dev \
          libgl1-mesa-dev \
          libdbus-1-dev \
          libudev-dev \
          libgles2-mesa-dev \
          libegl1-mesa-dev \
          libibus-1.0-dev \
          fcitx-libs-dev \
          libsamplerate0-dev \
          libpipewire-0.3-dev \
          libwayland-dev \
          libdecor-0-dev \
          libdrm-dev \
          libgbm-dev \
          libpng-dev \
          zlib1g-dev \
          libbz2-dev
    
    - name: Create build directories
      run: |
        mkdir -p build/SDL2
        mkdir -p build/freetype
        mkdir -p prebuilt/linux/x86_64
    
    - name: Build SDL2
      run: |
        cd build/SDL2
        cmake ../../SDL2-2.32.4 \
          -GNinja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=$PWD/../../prebuilt/linux/x86_64 \
          -DSDL_SHARED=ON \
          -DSDL_STATIC=ON \
          -DSDL_ALSA=ON \
          -DSDL_PULSEAUDIO=ON \
          -DSDL_X11=ON \
          -DSDL_WAYLAND=ON \
          -DSDL_OPENGL=ON \
          -DSDL_OPENGLES=ON \
          -DSDL_VULKAN=ON
        ninja
        ninja install
    
    - name: Build FreeType
      run: |
        cd build/freetype
        cmake ../../freetype-2.14.1 \
          -GNinja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=$PWD/../../prebuilt/linux/x86_64 \
          -DBUILD_SHARED_LIBS=ON \
          -DFT_DISABLE_HARFBUZZ=ON \
          -DFT_DISABLE_BROTLI=ON
        ninja
        ninja install
    
    - name: Create library info file
      run: |
        cat > prebuilt/linux/x86_64/library_info.txt << EOF
        Built on: $(date)
        Platform: Ubuntu $(lsb_release -rs)
        SDL2 Version: 2.32.4
        FreeType Version: 2.14.1
        
        Libraries:
        $(ls -la prebuilt/linux/x86_64/lib/)
        
        Headers:
        $(ls -la prebuilt/linux/x86_64/include/)
        EOF
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-x86_64-libraries
        path: prebuilt/linux/x86_64/
        retention-days: 30
    
    - name: List built files
      run: |
        echo "=== Built libraries ==="
        find prebuilt/linux/x86_64 -type f -name "*.so*" -o -name "*.a" | sort
        echo ""
        echo "=== Header files ==="
        find prebuilt/linux/x86_64/include -type f -name "*.h" | head -20